export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as ForgotPassword } from './ForgotPassword';
export { default as Orders } from './Orders';
export { default as OrderList } from './OrderList';
export { default as OrderDetail } from './OrderDetail';
export { default as Products } from './Products';
export { default as Users } from './Users';
export { default as LandingPage } from './LandingPage';
